site:
    name:           My Application
    description:    A sample application created using the Silex microframework.
    author:         Kalman Olah
    keywords:       just, a, few, tags, for, my, beloved, web, crawlers